---

- name: Run ansible-lint on playbooks
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Clone Git repository with playbooks
      ansible.builtin.git:
        repo: '{{ git_repo_url }}'
        dest: /tmp/playbooks
        force: true
      register: git_clone

    - name: Execute ansible-lint
      ansible.builtin.command:
        cmd: ansible-lint -v /tmp/playbooks/
      register: lint_result
      ignore_errors: true
      check_mode: false
      changed_when: true

    - name: Display ansible-lint results
      ansible.builtin.debug:
        var: lint_result.stdout_lines

    - name: Fail if ansible-lint found issues
      ansible.builtin.fail:
        msg: "ansible-lint found issues in the playbooks."
      when: lint_result.rc != 0
