---

- name: Run Molecule Tests
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Execute Molecule Test
      ansible.builtin.command: molecule test
      args:
        chdir: "{{ item }}"
      with_items:
        - ../roles/role1
        - ../roles/role2
      register: molecule_results
      ignore_errors: true
      changed_when: false

    - name: Display Molecule Test Results
      ansible.builtin.debug:
        var: molecule_results.results
